# **Model Benchmarks and Tuning**

### **Imports**
---

In [281]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn import metrics

### **Load the data**
-----

In [282]:
train = pd.read_csv('../data/train_engineered.csv')
print(train.shape)
train.head()

(1272, 249)

,Id,parcel_id,zoning_type,lot_frontage,lot_area,util_avail,year_built,year_remodeled,masonry_veneer_area,exterior_quality,...,sale_type_ConLw,sale_type_New,sale_type_Oth,sale_type_VWD,sale_type_WD,finished_space,basement_space,garage_yr_built_comb,total_bathrooms,total_living_area
0,544,531379050,RL,43.0,11492.0,AllPub,1996,1997,132.0,3,...,0,0,0,0,1,0.0,251988.0,3986012.0,4,2759.0
1,153,535304180,RL,68.0,7922.0,AllPub,1953,2007,0.0,2,...,0,0,0,0,1,0.0,344582.0,3814209.0,2,1788.0
2,318,916386060,RL,73.0,9802.0,AllPub,2006,2007,0.0,2,...,0,0,0,0,1,0.0,147456.0,4026042.0,3,1444.0
3,255,906425045,RL,82.0,14235.0,AllPub,1900,1993,0.0,2,...,0,0,0,0,1,0.0,456976.0,3718300.0,2,1445.0
4,2827,908186070,RM,35.0,3675.0,AllPub,2005,2006,82.0,2,...,0,1,0,0,0,0.0,0.0,4020025.0,3,1619.0

In [283]:
test = pd.read_csv('../data/test_engineered.csv')
print(test.shape)
test.head()

(878, 249)

,Id,parcel_id,zoning_type,lot_frontage,lot_area,util_avail,year_built,year_remodeled,masonry_veneer_area,exterior_quality,...,sale_type_ConLw,sale_type_New,sale_type_Oth,sale_type_VWD,sale_type_WD,finished_space,basement_space,garage_yr_built_comb,total_bathrooms,total_living_area
0,2658,902301120,RM,69.0,9142.0,AllPub,1910,1950,0.0,2,...,0,0,0,0,1,0.0,1040400.0,3648100.0,2,1928.0
1,2718,905108090,RL,NaN,9662.0,AllPub,1977,1977,0.0,2,...,0,0,0,0,1,0.0,3869089.0,3908529.0,2,1967.0
2,2414,528218130,RL,58.0,17104.0,AllPub,2006,2006,0.0,3,...,0,1,0,0,0,0.0,65400.0,4024036.0,4,2050.0
3,1989,902207150,RM,60.0,8520.0,AllPub,1923,2006,0.0,3,...,0,0,0,0,1,0.0,937024.0,3721005.0,1,968.0
4,625,535105100,RL,NaN,9500.0,AllPub,1963,1963,247.0,2,...,0,0,0,0,1,0.0,1094290.0,3853369.0,3,2003.0

### Model Benchmark

In [284]:
# add features from strongest model so far
features = [col for col in test._get_numeric_data().columns if col != 'SalePrice' and test[col].isnull().sum() == 0 and col not in ['zoning_type_I (all)',
            'util_avail_NoSewr', 'ames_neighborhood_BrDale', 'prox_to_transport_2_PosA', 'floors_2.5Fin', 'roof_material_Metal', 'roof_material_Roll',
            'roof_material_WdShngl', 'ext_covering_AsphShn', 'ext_covering_PreCast', 'ext_covering2_Other', 'ext_covering2_PreCast', 'masonry_veneer_type_CBlock',
            'masonry_veneer_type_nan', 'foundation_type_Slab', 'basement_finished_rating_nan', 'basement_finished_rating2_nan', 'heating_type_GasA',
            'full_bathrooms_above_ground_4', 'kitchens_above_ground_1', 'garage_finished_nan', 'garage_car_capacity_1', 'sale_type_VWD', 'basement_space','finished_space']]

In [285]:
#this code was adapted from lesson 3.02 on linear regression metrics
X = train[features]
y = train['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

print(f'Training Shape: {X_train.shape, y_train.shape}')
print(f'Test Shape: {X_test.shape, y_test.shape}')

lr = LinearRegression()
lr.fit(X_train, y_train)

Training Shape: ((954, 213), (954,))
Test Shape: ((318, 213), (318,))

LinearRegression()

In [286]:
#mean of Y
null_preds = y.mean()
null_preds

167024.4536163522

In [287]:
null_residuals = y - null_preds
null_residuals

0        52975.546384
1       -58024.453616
2         6975.546384
3       -28524.453616
4       -27024.453616
            ...
1267     14975.546384
1268    131726.546384
1269      9975.546384
1270    -23024.453616
1271     21975.546384
Name: SalePrice, Length: 1272, dtype: float64

In [288]:
#null MSE
null_sse = sum(null_residuals ** 2)
null_mse = null_sse / len(null_residuals)
null_mse

2731353010.3311806

## Comparing Metrics from highest scoring model

In [289]:
#Latest model MSE
lr.fit(X_train, y_train)
preds = lr.predict(X_test)

model_sse = metrics.mean_squared_error(y_test, preds)
model_sse

280931582.6654828

In [290]:
print(f'Training score: {lr.score(X_train, y_train)}')
print(f'Test score: {lr.score(X_test, y_test)}')
print(f'Cross validation score: {cross_val_score(lr, X_train, y_train).mean()}')

Training score: 0.9430456103366734
Test score: 0.8971282915143795
Cross validation score: 0.8854282160088804

----
# Production Model
### Balancing Performance with Interpretability
### Pre-Feature Engineering Dataset: Testing Simpler models

In [291]:
# read in the pre-engineered datasets
train = pd.read_csv('../data/train_preprocessed.csv')
test = pd.read_csv('../data/test_preprocessed.csv')

In [292]:
train.corr()[['SalePrice','ames_neighborhood_Blueste','ames_neighborhood_BrDale','ames_neighborhood_BrkSide','ames_neighborhood_ClearCr',
              'ames_neighborhood_Crawfor','ames_neighborhood_Edwards','ames_neighborhood_Gilbert','ames_neighborhood_Greens',
              'ames_neighborhood_IDOTRR','ames_neighborhood_MeadowV','ames_neighborhood_Mitchel',
              'ames_neighborhood_NoRidge', 'ames_neighborhood_NPkVill','ames_neighborhood_NridgHt','ames_neighborhood_NridgHt',
              'ames_neighborhood_NWAmes','ames_neighborhood_OldTown','ames_neighborhood_SWISU','ames_neighborhood_Sawyer',
              'ames_neighborhood_SawyerW','ames_neighborhood_Somerst','ames_neighborhood_StoneBr','ames_neighborhood_Timber',
              'ames_neighborhood_Veenker']].sort_values(by = 'SalePrice', ascending = False)

,SalePrice,ames_neighborhood_Blueste,ames_neighborhood_BrDale,ames_neighborhood_BrkSide,ames_neighborhood_ClearCr,ames_neighborhood_Crawfor,ames_neighborhood_Edwards,ames_neighborhood_Gilbert,ames_neighborhood_Greens,ames_neighborhood_IDOTRR,...,ames_neighborhood_NridgHt,ames_neighborhood_NWAmes,ames_neighborhood_OldTown,ames_neighborhood_SWISU,ames_neighborhood_Sawyer,ames_neighborhood_SawyerW,ames_neighborhood_Somerst,ames_neighborhood_StoneBr,ames_neighborhood_Timber,ames_neighborhood_Veenker
SalePrice,1.000000,0.005107,NaN,-0.149647,0.020886,0.076874,-0.217773,0.081425,0.020135,-0.211633,...,0.330672,0.057714,-0.284086,-0.105902,-0.123953,0.078677,0.292388,0.093131,0.183046,0.083328
exterior_quality,0.688407,0.048654,NaN,-0.116052,0.005160,-0.027442,-0.153874,0.078154,0.059612,-0.159293,...,0.323150,-0.083653,-0.199460,-0.085550,-0.144296,0.153516,0.316527,0.109681,0.122646,0.062529
year_built,0.667750,0.024446,NaN,-0.269984,-0.004285,-0.183204,-0.108243,0.236408,0.013736,-0.239889,...,0.236250,0.046395,-0.490041,-0.158269,-0.051204,0.160766,0.312922,0.075715,0.150350,0.034631
basement_height,0.663840,0.031225,NaN,-0.177863,0.010856,-0.041508,-0.119082,0.170900,0.038258,-0.165278,...,0.284854,0.034957,-0.311870,-0.088554,-0.124310,0.139443,0.252558,0.091954,0.159173,0.036555
above_ground_living_area,0.649481,-0.031262,NaN,-0.069661,0.057349,0.088018,-0.127826,0.105537,-0.023446,-0.074548,...,0.151466,0.107321,-0.023845,-0.027366,-0.165208,0.071310,0.112743,0.014575,0.077045,0.012336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
foundation_type_Slab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
basement_finished_rating_nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
basement_finished_rating2_nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
garage_finished_nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sale_type_VWD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Neighborhoods negatively correlated to sale price: 

BrkSide: -0.149647

Edwards: -0.217773

IDOTRR: -0.211633

OldTown: -0.284086

SWISU: -0.105902

Sawyer: -0.123953

In [293]:
high_corr_df = (train.corr()[['SalePrice']] > 0.45)
high_corr_df = high_corr_df[high_corr_df['SalePrice'] == True]
high_corr_df

                              SalePrice
year_built                         True
year_remodeled                     True
exterior_quality                   True
basement_height                    True
total_basement_area                True
heating_quality                    True
first_fl_area                      True
above_ground_living_area           True
full_bathrooms_above_ground        True
kitchen_quality                    True
garage_yr_built                    True
garage_size                        True
SalePrice                          True
house_quality_8                    True
foundation_type_PConc              True
basement_finished_rating_GLQ       True
garage_car_capacity_3              True

In [314]:
low_corr_df = (train.corr()[['SalePrice']] < -0.35)
low_corr_df = low_corr_df[low_corr_df['SalePrice'] == True]
low_corr_df

                          SalePrice
pool_quality                   True
house_quality_5                True
masonry_veneer_type_None       True
foundation_type_CBlock         True
garage_location_Detchd         True
garage_finished_Unf            True
garage_car_capacity_1          True

In [315]:
X = train[['bedrooms_above_ground','exterior_quality','year_built','basement_height','above_ground_living_area','full_bathrooms_above_ground','kitchen_quality','house_quality_5','masonry_veneer_type_None','garage_location_Detchd','garage_finished_Unf','garage_car_capacity_1']]
y = train['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

lr = LinearRegression()
lr.fit(X_train, y_train)

print(f'Training score: {lr.score(X_train, y_train)}')
print(f'Test score: {lr.score(X_test, y_test)}')
print(f'Cross validation score: {cross_val_score(lr, X_train, y_train).mean()}')

Training score: 0.7735923288289577
Test score: 0.8020045103256563
Cross validation score: 0.7663736134273188

In [303]:
# Now scaled

X = train[['bedrooms_above_ground','exterior_quality','year_built','basement_height','above_ground_living_area','full_bathrooms_above_ground','kitchen_quality','house_quality_5','masonry_veneer_type_None','garage_location_Detchd','garage_finished_Unf','garage_car_capacity_1','foundation_type_CBlock']]
y = train['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

ss = StandardScaler()
Z_train = ss.fit_transform(X_train)
Z_test = ss.transform(X_test)

lr = LinearRegression()
lr.fit(Z_train, y_train)

print(f'Training score: {lr.score(Z_train, y_train)}')
print(f'Test score: {lr.score(Z_test, y_test)}')
print(f'Cross validation score: {cross_val_score(lr, X_train, y_train).mean()}')

Training score: 0.7736481176007975
Test score: 0.8022094312151332
Cross validation score: 0.7662521725425802

In [304]:
preds = lr.predict(Z_test)

In [305]:
# RMSE
np.sqrt(metrics.mean_squared_error(y_test, preds))

23241.015284190307

In [306]:
# Compare to null Root Mean Squared error
np.sqrt(null_mse)

52262.34792210526

In [307]:
# The linear regression model's predicted home prices are off by about $23,265 relative to observed home prices,
# whereas the null model is off by about $52,262

In [308]:
coef_df = pd.DataFrame(lr.coef_, index = X.columns, columns = ['Coefficients'])
coef_df.sort_values(by = 'Coefficients', ascending = False)

                             Coefficients
above_ground_living_area     24145.293756
year_built                   11647.139176
kitchen_quality               9242.816552
exterior_quality              8598.676705
basement_height               4149.252805
foundation_type_CBlock         508.995157
house_quality_5                -84.318460
garage_car_capacity_1        -1392.559961
garage_finished_Unf          -1427.561657
full_bathrooms_above_ground  -2533.235231
garage_location_Detchd       -2989.019477
masonry_veneer_type_None     -4098.645447
bedrooms_above_ground        -4239.960241

In [302]:
train.corr()[['SalePrice']]

                 SalePrice
Id               -0.047748
parcel_id        -0.214173
lot_frontage      0.287084
lot_area          0.293859
year_built        0.667750
...                    ...
sale_type_ConLw  -0.050995
sale_type_New     0.267892
sale_type_Oth    -0.037267
sale_type_VWD          NaN
sale_type_WD     -0.103326

[248 rows x 1 columns]